// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Generates personalized introductory text for client testimonials using AI.
 *
 * - generatePersonalizedIntro - A function that generates personalized introductory text for a client testimonial.
 * - GeneratePersonalizedIntroInput - The input type for the generatePersonalizedIntro function.
 * - GeneratePersonalizedIntroOutput - The return type for the generatePersonalizedIntro function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GeneratePersonalizedIntroInputSchema = z.object({
  clientName: z.string().describe('The name of the client providing the testimonial.'),
  clientTitle: z.string().describe('The title of the client providing the testimonial (e.g., CEO, Manager).'),
  companyName: z.string().describe('The name of the client\u2019s company.'),
  testimonialText: z.string().describe('The full text of the client testimonial.'),
  productOrService: z.string().describe('The specific product or service the testimonial is about (e.g., \"Surety Bonds\").'),
});

export type GeneratePersonalizedIntroInput = z.infer<typeof GeneratePersonalizedIntroInputSchema>;

const GeneratePersonalizedIntroOutputSchema = z.object({
  introduction: z.string().describe('A personalized introductory text for the client testimonial.'),
});

export type GeneratePersonalizedIntroOutput = z.infer<typeof GeneratePersonalizedIntroOutputSchema>;

export async function generatePersonalizedIntro(input: GeneratePersonalizedIntroInput): Promise<GeneratePersonalizedIntroOutput> {
  return generatePersonalizedIntroFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generatePersonalizedIntroPrompt',
  input: {schema: GeneratePersonalizedIntroInputSchema},
  output: {schema: GeneratePersonalizedIntroOutputSchema},
  prompt: `You are an AI assistant specialized in creating personalized introductory text for client testimonials.
  Your goal is to generate a concise and engaging introduction that highlights the key benefits and context of the testimonial.

  Given the following information, create a personalized introduction for the testimonial:

  Client Name: {{{clientName}}}
  Client Title: {{{clientTitle}}}
  Company Name: {{{companyName}}}
  Testimonial Text: {{{testimonialText}}}
  Product/Service: {{{productOrService}}}

  The introduction should be no more than two sentences and should clearly state the client's experience and the value they received from the product or service.
  Focus on making the testimonial more relatable and impactful for potential customers.
  The introduction should be in Spanish (Spain).
`,
});

const generatePersonalizedIntroFlow = ai.defineFlow(
  {
    name: 'generatePersonalizedIntroFlow',
    inputSchema: GeneratePersonalizedIntroInputSchema,
    outputSchema: GeneratePersonalizedIntroOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
