// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Generates personalized introductory text for client testimonials using AI.
 *
 * - generatePersonalizedIntro - A function that generates personalized introductory text for a protegido testimonial.
 * - GeneratePersonalizedIntroInput - The input type for the generatePersonalizedIntro function.
 * - GeneratePersonalizedIntroOutput - The return type for the generatePersonalizedIntro function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GeneratePersonalizedIntroInputSchema = z.object({
  protegidoName: z.string().describe('The name of the protegido providing the testimonial.'),
  protegidoTitle: z.string().describe('The title of the protegido providing the testimonial (e.g., CEO, Manager).'),
  companyName: z.string().describe('The name of the protegido’s company.'),
  testimonialText: z.string().describe('The full text of the protegido testimonial.'),
  productOrService: z.string().describe('The specific product or service the testimonial is about (e.g., "Surety Bonds").'),
});

export type GeneratePersonalizedIntroInput = z.infer<typeof GeneratePersonalizedIntroInputSchema>;

const GeneratePersonalizedIntroOutputSchema = z.object({
  introduction: z.string().describe('A personalized introductory text for the protegido testimonial.'),
});

export type GeneratePersonalizedIntroOutput = z.infer<typeof GeneratePersonalizedIntroOutputSchema>;

export async function generatePersonalizedIntro(input: GeneratePersonalizedIntroInput): Promise<GeneratePersonalizedIntroOutput> {
  return generatePersonalizedIntroFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generatePersonalizedIntroPrompt',
  input: {schema: GeneratePersonalizedIntroInputSchema},
  output: {schema: GeneratePersonalizedIntroOutputSchema},
  prompt: `You are an AI assistant specialized in creating personalized introductory text for client testimonials for a Spanish insurance agency named "CONFÍA".
  Your goal is to generate a concise and engaging introduction that highlights the key benefits and context of the testimonial.

  Given the following information, create a personalized introduction for the testimonial:

  Client Name: {{{protegidoName}}}
  Client Title: {{{protegidoTitle}}}
  Company Name: {{{companyName}}}
  Testimonial Text: {{{testimonialText}}}
  Product/Service: {{{productOrService}}}

  The introduction should be **one single sentence**, summarizing the client's main success or solved problem, and linking it to the company name and service.
  The tone should be professional and impactful.
  The output MUST be in Spanish (Spain).

  Example:
  Input: { protegidoName: 'Javier', companyName: 'G-Construct', productOrService: 'Seguro de Caución', testimonialText: 'El cambio a los seguros de caución con CONFÍA ha sido un antes y un después. Ahora podemos presentarnos a más concursos sin preocuparnos por el impacto en nuestras líneas de crédito.' }
  Output: { introduction: 'Para G-Construct, la agilidad en la obtención de garantías para licitaciones es crucial. CONFÍA nos ha proporcionado una solución rápida y sin el consumo de recursos que suponían los avales bancarios.' }
`,
});

const generatePersonalizedIntroFlow = ai.defineFlow(
  {
    name: 'generatePersonalizedIntroFlow',
    inputSchema: GeneratePersonalizedIntroInputSchema,
    outputSchema: GeneratePersonalizedIntroOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
