// This is an autogenerated file from Firebase Studio.
import { MetadataRoute } from 'next'

export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: '*',
      allow: '/',
    },
    sitemap: 'https://www.confiax.es/sitemap.xml',
  }
}
