// This is an autogenerated file from Firebase Studio.
import { MetadataRoute } from 'next'

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = 'https://www.confiax.es';

  const staticRoutes = [
    '/',
    '/seguro-caucion',
    '/soluciones',
    '/nosotros',
    '/contacto',
    '/ventajas',
    '/politica-privacidad',
    '/politica-cookies',
    '/aviso-legal',
  ];

  return staticRoutes.map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified: new Date(),
    changeFrequency: 'weekly',
    priority: route === '/' ? 1 : 0.8,
  }));
}
